let allItems=[],allFeeds=[],activeFilter='all',activeCategory='all';
const stageNames={20:'Preparación',30:'Comité',40:'Consulta',50:'Aprobación',60:'Publicación',90:'Revisión',95:'Retirada'};
const categoryIcons={'Gestión SST':'◎','Higiene ocupacional':'◉','Ergonomía':'↔','Psicosocial':'◌','Clima y ambiente':'☀','Emergencias':'⚠','EPP':'⬟','Salud laboral':'✚','Trabajo y tecnología':'⌘'};
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function fmtDate(s){if(!s)return'—';if(/^\d{4}-\d{2}$/.test(s)){const[y,m]=s.split('-');return new Intl.DateTimeFormat('es',{month:'short',year:'numeric'}).format(new Date(+y,+m-1,1))}const d=new Date(s+'T12:00:00');return isNaN(d)?s:new Intl.DateTimeFormat('es',{day:'2-digit',month:'short',year:'numeric'}).format(d)}
function bucket(x){const n=parseInt(x.stage||0,10);if(n===90||n===95)return'review';if(n>=60)return'published';return'development'}
function badge(x){const b=bucket(x);return b==='published'?['Publicada','pub']:b==='review'?['Revisión','rev']:['En desarrollo','dev']}
function render(){const q=$('#searchInput').value.trim().toLowerCase();const items=allItems.filter(x=>(activeFilter==='all'||bucket(x)===activeFilter)&&(activeCategory==='all'||x.category===activeCategory)&&(!q||[x.reference,x.topic,x.title,x.description,x.stage,x.category,x.committee].join(' ').toLowerCase().includes(q)));
$('#cards').innerHTML=items.map(x=>{const [label,cls]=badge(x),major=parseInt(x.stage||0,10);return `<article class="card"><div class="card-top"><div><div class="ref">${esc(x.reference)}</div><span class="category-tag">${esc(categoryIcons[x.category]||'•')} ${esc(x.category||'SST')}</span></div><span class="badge ${cls}">${label}</span></div><div class="topic">${esc(x.topic)}</div><div class="title">${esc(x.title)}</div><div class="meta"><div><small>Etapa ISO</small><b>${esc(x.stage||'—')} · ${esc(stageNames[major]||'')}</b></div><div><small>Último cambio</small><b>${fmtDate(x.pubDate)}</b></div></div>${x.committee?`<div class="committee">${esc(x.committee)}</div>`:''}<p class="desc">${esc(x.description||'Actualización disponible en ISO.org.')}</p><div class="card-actions"><span><i class="source-dot"></i>RSS oficial</span><a href="${esc(x.link)}" target="_blank" rel="noopener">Ver en ISO ↗</a></div></article>`}).join('');$('#emptyState').hidden=items.length>0}
function renderCategories(){const cats=[...new Set(allFeeds.map(f=>f.category).filter(Boolean))].sort();$('#categorySelect').innerHTML='<option value="all">Todos los temas</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');$('#categoryTiles').innerHTML=cats.map(c=>{const n=allFeeds.filter(f=>f.category===c).length;return `<button class="category-tile" data-category="${esc(c)}"><span>${esc(categoryIcons[c]||'•')}</span><b>${esc(c)}</b><small>${n} fuente${n===1?'':'s'}</small></button>`}).join('');document.querySelectorAll('.category-tile').forEach(b=>b.addEventListener('click',()=>{activeCategory=b.dataset.category;$('#categorySelect').value=activeCategory;location.hash='radar';render()}))}
function renderSources(){const cats=[...new Set(allFeeds.map(f=>f.category).filter(Boolean))].sort();$('#sourceList').innerHTML=cats.map(c=>`<section class="source-group"><h3>${esc(categoryIcons[c]||'•')} ${esc(c)}</h3><div>${allFeeds.filter(f=>f.category===c).map(f=>`<div class="source-row"><span><b>${esc(f.reference)}</b><small>${esc(f.committee||'')}</small></span><a href="${esc(f.page)}" target="_blank" rel="noopener">ISO.org ↗</a></div>`).join('')}</div></section>`).join('')}
function stats(){$('#countTotal').textContent=allItems.length;$('#countDev').textContent=allItems.filter(x=>bucket(x)==='development').length;$('#countPub').textContent=allItems.filter(x=>bucket(x)==='published').length;$('#countReview').textContent=allItems.filter(x=>bucket(x)==='review').length}
async function init(){try{const[d,f]=await Promise.all([fetch('data/updates.json?ts='+Date.now()).then(r=>r.json()),fetch('data/feeds.json').then(r=>r.json())]);allFeeds=f.feeds||[];const fm=Object.fromEntries(allFeeds.map(x=>[x.id,x]));allItems=(d.items||[]).map(x=>({...fm[x.id],...x})).sort((a,b)=>(b.pubDate||'').localeCompare(a.pubDate||''));const dt=new Date(d.generated_at);$('#lastUpdate').textContent='Datos actualizados: '+(isNaN(dt)?'pendiente':new Intl.DateTimeFormat('es',{dateStyle:'medium',timeStyle:'short'}).format(dt));stats();renderCategories();render();renderSources()}catch(e){$('#cards').innerHTML='<div class="loading-card">No se pudieron cargar los datos. Intenta nuevamente en unos minutos.</div>';$('#lastUpdate').textContent='Actualización temporalmente no disponible'}}
$('#searchInput').addEventListener('input',render);$('#categorySelect').addEventListener('change',e=>{activeCategory=e.target.value;render()});document.querySelectorAll('.chip').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;render()}));init();